-- MySQL Script generated by MySQL Workbench
-- Wed Apr  3 17:39:22 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(45) NOT NULL,
  `Passcode` VARCHAR(100) NOT NULL,
  `FullName` VARCHAR(50) NOT NULL,
  `Age` INT NOT NULL,
  `Major` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Projects` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Projects` (
  `ProjectID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `AuthorID` INT NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`ProjectID`, `AuthorID`),
  UNIQUE INDEX `ProjectID_UNIQUE` (`ProjectID` ASC) VISIBLE,
  INDEX `AuthorID_idx` (`AuthorID` ASC) VISIBLE,
  CONSTRAINT `AuthorID`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `mydb`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Comments` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Comments` (
  `CommentID` INT NOT NULL AUTO_INCREMENT,
  `AuthorID` INT NOT NULL,
  `Body` VARCHAR(250) NULL,
  `Timestamp` DATETIME NOT NULL,
  `ProjectID` INT NOT NULL,
  PRIMARY KEY (`CommentID`),
  UNIQUE INDEX `UserID_UNIQUE` (`CommentID` ASC) VISIBLE,
  INDEX `AuthorID_idx` (`AuthorID` ASC) VISIBLE,
  INDEX `ProjectID_idx` (`ProjectID` ASC) VISIBLE,
  CONSTRAINT `AuthorID`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `mydb`.`Users` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProjectID`
    FOREIGN KEY (`ProjectID`)
    REFERENCES `mydb`.`Projects` (`ProjectID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
